.class public abstract Lcom/netflix/hawkins/consumer/tokens/Token$Color;
.super Lcom/netflix/hawkins/consumer/tokens/Token;
.source ""


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lcom/netflix/hawkins/consumer/tokens/Token;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x409
    name = "Color"
.end annotation

.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$a;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$c;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$e;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$b;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$d;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$h;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$g;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$i;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$f;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$j;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$m;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$k;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$n;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$l;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$o;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$p;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$t;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$s;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$q;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$r;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$w;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$u;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$v;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$y;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$x;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$A;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$z;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$C;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$B;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$D;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$H;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$I;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$F;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$G;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$E;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$K;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$N;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$L;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$M;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$J;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$R;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$S;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$P;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$O;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$Q;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$W;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$U;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$T;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$X;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$V;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$Z;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ac;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aa;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ab;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$Y;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ae;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ah;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$af;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ad;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ag;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ai;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$al;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$am;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ak;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ap;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ar;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$an;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ao;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$as;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$av;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$au;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$at;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$az;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ax;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ay;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ba;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$aY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bb;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bf;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bd;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bc;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$be;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bi;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bk;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bh;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bn;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bl;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bp;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bo;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bm;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bu;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bt;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bs;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$br;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$by;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bx;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cc;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cb;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cd;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$bZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ca;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ch;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cf;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ci;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ce;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cm;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cn;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ck;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cl;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$co;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cs;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cp;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cr;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ct;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cx;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cu;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cy;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$db;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$da;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$cY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dc;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$df;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dd;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$de;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$di;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dk;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dl;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dh;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$do;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dn;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dp;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dm;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dr;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dt;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$du;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ds;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dx;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dy;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$dZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eb;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ee;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ec;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ed;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ea;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ef;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ei;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ej;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eh;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$el;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ek;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$em;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$en;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eo;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$er;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ep;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$es;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$et;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ex;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ev;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ew;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$Group;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ey;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eu;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ez;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fc;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fa;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fb;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$eZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fd;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fe;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fh;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ff;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fm;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fi;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fk;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fl;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fp;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fn;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fr;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fo;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fs;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ft;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fu;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fy;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fx;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ga;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$fY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gb;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gf;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gd;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gc;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ge;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gi;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gh;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gk;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gp;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gm;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$go;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gl;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gn;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gu;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gs;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gt;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gr;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gy;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gx;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hb;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hd;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hc;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ha;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$gZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$he;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hf;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hh;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hi;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hm;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hn;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hk;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hl;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hp;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hr;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ho;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hs;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ht;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hu;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hx;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hy;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ia;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$hZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ib;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$id;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ie;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ig;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ic;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$if;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ih;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$il;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ii;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ik;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ij;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$im;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ip;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$io;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$in;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ir;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iu;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$it;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$is;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ix;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iy;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$iZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jc;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jd;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ja;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jb;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$je;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jh;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ji;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jf;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jo;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jm;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jk;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jl;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jn;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$js;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jr;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jp;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jt;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jx;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ju;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jy;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jX;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jW;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jT;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jU;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kb;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kc;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ka;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jY;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$jZ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kd;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kh;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kf;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kg;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ke;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kl;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kk;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ki;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kj;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$km;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kn;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kr;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kp;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ko;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kq;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ku;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kv;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ks;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kt;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kw;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kA;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kx;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kz;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$ky;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kB;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kC;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kE;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kF;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kD;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kG;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kK;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kI;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kL;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kH;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kJ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kO;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kP;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kN;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kM;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kQ;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kV;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kR;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kS;,
        Lcom/netflix/hawkins/consumer/tokens/Token$Color$kU;
    }
.end annotation


# static fields
.field public static final c:Lcom/netflix/hawkins/consumer/tokens/Token$Color$cK;


# instance fields
.field private final b:Lcom/netflix/hawkins/consumer/tokens/Token$Color$Group;

.field private final e:Ljava/util/Map;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/Map<",
            "Lcom/netflix/hawkins/consumer/tokens/Appearance;",
            "Lcom/netflix/hawkins/consumer/tokens/Token$Color$jL;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method static constructor <clinit>()V
    .locals 2

    .line 0
    new-instance v0, Lcom/netflix/hawkins/consumer/tokens/Token$Color$cK;

    const/4 v1, 0x0

    invoke-direct {v0, v1}, Lcom/netflix/hawkins/consumer/tokens/Token$Color$cK;-><init>(B)V

    sput-object v0, Lcom/netflix/hawkins/consumer/tokens/Token$Color;->c:Lcom/netflix/hawkins/consumer/tokens/Token$Color$cK;

    return-void
.end method

.method private constructor <init>(Ljava/lang/String;Lcom/netflix/hawkins/consumer/tokens/Token$Color$Group;Ljava/util/Map;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/lang/String;",
            "Lcom/netflix/hawkins/consumer/tokens/Token$Color$Group;",
            "Ljava/util/Map<",
            "Lcom/netflix/hawkins/consumer/tokens/Appearance;",
            "Lcom/netflix/hawkins/consumer/tokens/Token$Color$jL;",
            ">;)V"
        }
    .end annotation

    const/4 v0, 0x0

    .line 12
    invoke-direct {p0, p1, v0}, Lcom/netflix/hawkins/consumer/tokens/Token;-><init>(Ljava/lang/String;B)V

    iput-object p2, p0, Lcom/netflix/hawkins/consumer/tokens/Token$Color;->b:Lcom/netflix/hawkins/consumer/tokens/Token$Color$Group;

    iput-object p3, p0, Lcom/netflix/hawkins/consumer/tokens/Token$Color;->e:Ljava/util/Map;

    return-void
.end method

.method public synthetic constructor <init>(Ljava/lang/String;Lcom/netflix/hawkins/consumer/tokens/Token$Color$Group;Ljava/util/Map;B)V
    .locals 0

    .line 0
    invoke-direct {p0, p1, p2, p3}, Lcom/netflix/hawkins/consumer/tokens/Token$Color;-><init>(Ljava/lang/String;Lcom/netflix/hawkins/consumer/tokens/Token$Color$Group;Ljava/util/Map;)V

    return-void
.end method


# virtual methods
.method public final b()Ljava/util/Map;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/Map<",
            "Lcom/netflix/hawkins/consumer/tokens/Appearance;",
            "Lcom/netflix/hawkins/consumer/tokens/Token$Color$jL;",
            ">;"
        }
    .end annotation

    .line 12
    iget-object v0, p0, Lcom/netflix/hawkins/consumer/tokens/Token$Color;->e:Ljava/util/Map;

    return-object v0
.end method
